"""
Mock card data seeder - One Piece TCG Starter Deck ST-01 (Straw Hat Crew)
Seeds the database with realistic card data for development/testing.
"""
from app.database import async_session
from app.models import Card
from sqlalchemy import select

MOCK_CARDS = [
    # ===== LEADER =====
    {
        "card_number": "ST01-001",
        "name": "Monkey.D.Luffy",
        "name_cn": "蒙奇·D·路飞",
        "card_type": "LEADER",
        "color": "RED",
        "cost": 0,
        "power": 5000,
        "counter": 0,
        "life": 5,
        "attribute": "Strike",
        "effect": "[Activate: Main] [Once Per Turn] Give up to 1 rested DON!! card to this Leader or 1 of your Characters.",
        "trigger": "",
        "trait": "Supernovas/Straw Hat Crew",
        "rarity": "L",
        "set_code": "ST01",
    },
    # ===== CHARACTERS =====
    {
        "card_number": "ST01-002",
        "name": "Usopp",
        "name_cn": "乌索普",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 2,
        "power": 2000,
        "counter": 1000,
        "life": 0,
        "attribute": "Ranged",
        "effect": "",
        "trigger": "",
        "trait": "Straw Hat Crew",
        "rarity": "C",
        "set_code": "ST01",
    },
    {
        "card_number": "ST01-003",
        "name": "Karoo",
        "name_cn": "跑得快",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 1,
        "power": 3000,
        "counter": 1000,
        "life": 0,
        "attribute": "Strike",
        "effect": "",
        "trigger": "",
        "trait": "Alabasta/Animal",
        "rarity": "C",
        "set_code": "ST01",
    },
    {
        "card_number": "ST01-004",
        "name": "Sanji",
        "name_cn": "山治",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 2,
        "power": 3000,
        "counter": 2000,
        "life": 0,
        "attribute": "Strike",
        "effect": "",
        "trigger": "",
        "trait": "Straw Hat Crew",
        "rarity": "C",
        "set_code": "ST01",
    },
    {
        "card_number": "ST01-005",
        "name": "Jinbe",
        "name_cn": "甚平",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 3,
        "power": 4000,
        "counter": 1000,
        "life": 0,
        "attribute": "Strike",
        "effect": "",
        "trigger": "",
        "trait": "Fish-Man/Straw Hat Crew",
        "rarity": "C",
        "set_code": "ST01",
    },
    {
        "card_number": "ST01-006",
        "name": "Tony Tony.Chopper",
        "name_cn": "托尼托尼·乔巴",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 1,
        "power": 1000,
        "counter": 2000,
        "life": 0,
        "attribute": "Strike",
        "effect": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
        "trigger": "",
        "trait": "Animal/Straw Hat Crew",
        "rarity": "C",
        "set_code": "ST01",
    },
    {
        "card_number": "ST01-007",
        "name": "Nami",
        "name_cn": "娜美",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 1,
        "power": 2000,
        "counter": 1000,
        "life": 0,
        "attribute": "Special",
        "effect": "[On Play] Look at 5 cards from the top of your deck; reveal up to 1 [Straw Hat Crew] type card other than [Nami] and add it to your hand. Then, place the rest at the bottom of your deck in any order.",
        "trigger": "",
        "trait": "Straw Hat Crew",
        "rarity": "C",
        "set_code": "ST01",
    },
    {
        "card_number": "ST01-008",
        "name": "Nico Robin",
        "name_cn": "妮可·罗宾",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 3,
        "power": 5000,
        "counter": 1000,
        "life": 0,
        "attribute": "Strike",
        "effect": "",
        "trigger": "",
        "trait": "Straw Hat Crew",
        "rarity": "C",
        "set_code": "ST01",
    },
    {
        "card_number": "ST01-009",
        "name": "Franky",
        "name_cn": "弗兰奇",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 4,
        "power": 5000,
        "counter": 1000,
        "life": 0,
        "attribute": "Strike",
        "effect": "[On Play] Up to 1 of your {Straw Hat Crew} type Characters with a cost of 3 or less gains [Rush] until the end of this turn. (This card can attack on the turn in which it is played.)",
        "trigger": "",
        "trait": "Straw Hat Crew",
        "rarity": "C",
        "set_code": "ST01",
    },
    {
        "card_number": "ST01-010",
        "name": "Brook",
        "name_cn": "布鲁克",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 2,
        "power": 3000,
        "counter": 2000,
        "life": 0,
        "attribute": "Slash",
        "effect": "",
        "trigger": "",
        "trait": "Straw Hat Crew",
        "rarity": "C",
        "set_code": "ST01",
    },
    {
        "card_number": "ST01-011",
        "name": "Monkey.D.Luffy",
        "name_cn": "蒙奇·D·路飞",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 5,
        "power": 6000,
        "counter": 0,
        "life": 0,
        "attribute": "Strike",
        "effect": "[Rush] (This card can attack on the turn in which it is played.)",
        "trigger": "",
        "trait": "Supernovas/Straw Hat Crew",
        "rarity": "SR",
        "set_code": "ST01",
    },
    {
        "card_number": "ST01-012",
        "name": "Roronoa Zoro",
        "name_cn": "罗罗诺亚·索隆",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 3,
        "power": 5000,
        "counter": 0,
        "life": 0,
        "attribute": "Slash",
        "effect": "[DON!! x1] [When Attacking] This Character gains +1000 power during this battle.",
        "trigger": "",
        "trait": "Supernovas/Straw Hat Crew",
        "rarity": "SR",
        "set_code": "ST01",
    },
    # ===== EVENTS =====
    {
        "card_number": "ST01-013",
        "name": "Gum-Gum Jet Pistol",
        "name_cn": "橡胶橡胶 火箭炮",
        "card_type": "EVENT",
        "color": "RED",
        "cost": 4,
        "power": 0,
        "counter": 0,
        "life": 0,
        "attribute": "",
        "effect": "[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle.",
        "trigger": "[Trigger] Activate this card's [Counter] effect.",
        "trait": "Straw Hat Crew",
        "rarity": "C",
        "set_code": "ST01",
    },
    {
        "card_number": "ST01-014",
        "name": "Guard Point",
        "name_cn": "防御强化",
        "card_type": "EVENT",
        "color": "RED",
        "cost": 1,
        "power": 0,
        "counter": 0,
        "life": 0,
        "attribute": "",
        "effect": "[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle.",
        "trigger": "[Trigger] Activate this card's [Counter] effect.",
        "trait": "Straw Hat Crew",
        "rarity": "C",
        "set_code": "ST01",
    },
    {
        "card_number": "ST01-015",
        "name": "Diable Jambe",
        "name_cn": "恶魔风脚",
        "card_type": "EVENT",
        "color": "RED",
        "cost": 2,
        "power": 0,
        "counter": 0,
        "life": 0,
        "attribute": "",
        "effect": "[Main] K.O. up to 1 of your opponent's rested Characters with a cost of 3 or less.",
        "trigger": "",
        "trait": "Straw Hat Crew",
        "rarity": "C",
        "set_code": "ST01",
    },
    {
        "card_number": "ST01-016",
        "name": "Onigiri",
        "name_cn": "鬼斩",
        "card_type": "EVENT",
        "color": "RED",
        "cost": 3,
        "power": 0,
        "counter": 0,
        "life": 0,
        "attribute": "",
        "effect": "[Main] K.O. up to 1 of your opponent's rested Characters with a cost of 4 or less.",
        "trigger": "",
        "trait": "Supernovas/Straw Hat Crew",
        "rarity": "C",
        "set_code": "ST01",
    },
    # ===== STAGE =====
    {
        "card_number": "ST01-017",
        "name": "Thousand Sunny",
        "name_cn": "万里阳光号",
        "card_type": "STAGE",
        "color": "RED",
        "cost": 2,
        "power": 0,
        "counter": 0,
        "life": 0,
        "attribute": "",
        "effect": "[Activate: Main] [Once Per Turn] Give up to 1 rested DON!! card to your Leader or 1 of your Characters.",
        "trigger": "",
        "trait": "Straw Hat Crew",
        "rarity": "C",
        "set_code": "ST01",
    },
    # ===== SECOND LEADER (for 2nd player) =====
    {
        "card_number": "ST02-001",
        "name": "Shanks",
        "name_cn": "香克斯",
        "card_type": "LEADER",
        "color": "RED",
        "cost": 0,
        "power": 5000,
        "counter": 0,
        "life": 4,
        "attribute": "Slash",
        "effect": "[Activate: Main] [Once Per Turn] DON!! −1 (You may return the specified number of DON!! cards from your field to your DON!! deck): Give up to 1 of your Characters with an original power of 6000 or more [Rush] during this turn.",
        "trigger": "",
        "trait": "Film/Four Emperors/Red-Haired Pirates",
        "rarity": "L",
        "set_code": "ST02",
    },
    # ST02 Characters for the 2nd deck
    {
        "card_number": "ST02-002",
        "name": "Benn Beckman",
        "name_cn": "贝克曼",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 4,
        "power": 5000,
        "counter": 1000,
        "life": 0,
        "attribute": "Ranged",
        "effect": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
        "trigger": "",
        "trait": "Film/Red-Haired Pirates",
        "rarity": "C",
        "set_code": "ST02",
    },
    {
        "card_number": "ST02-003",
        "name": "Lucky Roux",
        "name_cn": "拉基·路",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 2,
        "power": 3000,
        "counter": 1000,
        "life": 0,
        "attribute": "Strike",
        "effect": "",
        "trigger": "",
        "trait": "Film/Red-Haired Pirates",
        "rarity": "C",
        "set_code": "ST02",
    },
    {
        "card_number": "ST02-004",
        "name": "Yasopp",
        "name_cn": "耶稣布",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 3,
        "power": 4000,
        "counter": 2000,
        "life": 0,
        "attribute": "Ranged",
        "effect": "",
        "trigger": "",
        "trait": "Film/Red-Haired Pirates",
        "rarity": "C",
        "set_code": "ST02",
    },
    {
        "card_number": "ST02-005",
        "name": "Shanks",
        "name_cn": "香克斯",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 7,
        "power": 7000,
        "counter": 0,
        "life": 0,
        "attribute": "Slash",
        "effect": "[Rush] (This card can attack on the turn in which it is played.)\n[Banish] (When this card deals damage, the target card is trashed instead of being placed in the owner's hand.)",
        "trigger": "",
        "trait": "Film/Red-Haired Pirates",
        "rarity": "SR",
        "set_code": "ST02",
    },
    {
        "card_number": "ST02-006",
        "name": "Rockstar",
        "name_cn": "洛克斯达",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 1,
        "power": 2000,
        "counter": 1000,
        "life": 0,
        "attribute": "Slash",
        "effect": "",
        "trigger": "",
        "trait": "Film/Red-Haired Pirates",
        "rarity": "C",
        "set_code": "ST02",
    },
    {
        "card_number": "ST02-007",
        "name": "Limejuice",
        "name_cn": "莱姆果汁",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 3,
        "power": 5000,
        "counter": 1000,
        "life": 0,
        "attribute": "Strike",
        "effect": "",
        "trigger": "",
        "trait": "Film/Red-Haired Pirates",
        "rarity": "C",
        "set_code": "ST02",
    },
    {
        "card_number": "ST02-008",
        "name": "Hongo",
        "name_cn": "本果",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 2,
        "power": 2000,
        "counter": 2000,
        "life": 0,
        "attribute": "Wisdom",
        "effect": "[Blocker]",
        "trigger": "",
        "trait": "Film/Red-Haired Pirates",
        "rarity": "C",
        "set_code": "ST02",
    },
    {
        "card_number": "ST02-009",
        "name": "Monster",
        "name_cn": "怪物",
        "card_type": "CHARACTER",
        "color": "RED",
        "cost": 5,
        "power": 6000,
        "counter": 1000,
        "life": 0,
        "attribute": "Strike",
        "effect": "[Double Attack] (This card deals 2 damage.)",
        "trigger": "",
        "trait": "Film/Red-Haired Pirates",
        "rarity": "R",
        "set_code": "ST02",
    },
    # ST02 Events
    {
        "card_number": "ST02-010",
        "name": "Gryphon",
        "name_cn": "格里芬",
        "card_type": "EVENT",
        "color": "RED",
        "cost": 2,
        "power": 0,
        "counter": 0,
        "life": 0,
        "attribute": "",
        "effect": "[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle.",
        "trigger": "[Trigger] Activate this card's [Counter] effect.",
        "trait": "Film/Red-Haired Pirates",
        "rarity": "C",
        "set_code": "ST02",
    },
    {
        "card_number": "ST02-011",
        "name": "Red Hair Pirates",
        "name_cn": "红发海贼团",
        "card_type": "EVENT",
        "color": "RED",
        "cost": 1,
        "power": 0,
        "counter": 0,
        "life": 0,
        "attribute": "",
        "effect": "[Main] Trash up to 1 of your opponent's Characters with 3000 or less power.",
        "trigger": "",
        "trait": "Film/Red-Haired Pirates",
        "rarity": "C",
        "set_code": "ST02",
    },
]


async def seed_mock_cards():
    """Seed mock cards into database if empty."""
    async with async_session() as session:
        result = await session.execute(select(Card).limit(1))
        if result.scalars().first() is not None:
            return  # Already seeded

        for card_data in MOCK_CARDS:
            card = Card(**card_data)
            session.add(card)

        await session.commit()
        print(f"[Seed] Inserted {len(MOCK_CARDS)} mock cards into database")
